### ISSUE TITLE
stl的lower_bound和upper_bound的函数功能解释有点问题。

### ISSUE THREAD

**Issue by blackhorse001** [huihut/interview#10]
lower_bound(ForwardIter first, ForwardIter last,const _Tp& val)算法返回一个非递减序列[first, last)中的第一个大于等于值val的位置。
upper_bound(ForwardIter first, ForwardIter last, const _Tp& val)算法返回一个非递减序列[first, last)中第一个大于val的位置。
![default](https://user-images.githubusercontent.com/42462589/44253794-4df90f80-a233-11e8-871d-66619cf5129e.PNG)

**Comment by huihut** [comment]
确实错了，这个是参考《C++ Primer 中文版（第五版）》773页的，看来书上翻译也错了

**Comment by huihut** [comment]
已改，感谢

**Comment by blackhorse001** [comment]
也谢谢楼主的无私。
