### ISSUE TITLE
堆排序的最坏情况的时间复杂度是不是写错了？

### ISSUE THREAD

**Issue by Ematrix163** [huihut/interview#17]
应该是O(logN).... 二叉堆呀

**Comment by huihut** [comment]
最坏情况好像和平均一样也是 O(n*log<sub>2</sub>n)

初始构建堆是 O(n)，一次重建堆是 O(log<sub>2</sub>n)，n 次重建堆是 O(n*log<sub>2</sub>n)，所以最终是 O(n*log<sub>2</sub>n + n) = O(n*log<sub>2</sub>n)

**Comment by Ematrix163** [comment]
> 最坏情况好像和平均一样也是 O(n*log2n)
> 
> 初始构建堆是 O(n)，一次重建堆是 O(log2n)，n 次重建堆是 O(n_log2n)，所以最终是 O(n_log2n + n) = O(n*log2n)

我打错了....我是想说最坏情况应该是O(n*log2n)，它上面的是O(n^2)

**Comment by huihut** [comment]
噢噢，对的，我那里写错了，感谢指出
