### ISSUE TITLE
CountSort.cpp可以執行嗎?

### ISSUE THREAD

**Issue by henryace** [huihut/interview#21]
Hello,

有人試過CountSort.cpp這個cpp檔可以正確執行嗎?

countSort function迴圈看起來是沒問題，可是執行完就錯誤

https://imgur.com/uyfZb7a.png

有人正常執行的嗎?

thx

**Comment by huihut** [comment]
是vector索引越界异常，等下修复一下

**Comment by huihut** [comment]
@henryace 剛剛更新了，現在應該沒問題了吧
https://github.com/huihut/interview/blob/master/Algorithm/CountSort.cpp

**Comment by henryace** [comment]
@huihut  Thank you! 👍
