### ISSUE TITLE
this指针的一个表述问题

### ISSUE THREAD

**Issue by FengZiYjun** [huihut/interview#26]
this指针第一行，“它指向正在被该成员函数操作的那个对象。”描述不恰当。建议改成“它指向调用该成员函数的那个对象”。

**Comment by oceanlvr** [comment]
> this指针第一行，“它指向正在被该成员函数操作的那个对象。”描述不恰当。建议改成“它指向调用该成员函数的那个对象”。

您好，这种说法有什么含义区别吗？（小白不太懂

**Comment by FengZiYjun** [comment]
> > this指针第一行，“它指向正在被该成员函数操作的那个对象。”描述不恰当。建议改成“它指向调用该成员函数的那个对象”。
> 
> 您好，这种说法有什么含义区别吗？（小白不太懂

"**被**成员函数**操作**的对象"，一般人的理解是函数接受的形参。
但其实this指针指向的对象，是作出函数调用 这个动作 的对象。不应该用上述被动句来定义。

**Comment by huihut** [comment]
@FengZiYjun 感谢，你可以提个PR，或者我晚上改。

**Comment by huihut** [comment]
已改
