### ISSUE TITLE
可能不准确的地方

### ISSUE THREAD

**Issue by shangjiaxuan** [huihut/interview#27]
翻到了这个指导，光看了readme的前几个部分就感觉十分有收获（到网络IO部分为止）。但是在看的同时对不熟悉的东西做了一下调查，觉得有下面几个地方可能可以优化一下？

1. inline 函数似乎原则上可以含有复杂一些的，如循环的操作，尽管可能编译器并不会内联。参考的是在stackoverflow的[讨论](https://stackoverflow.com/questions/13190326/loops-and-inline-functions)。

2. 并不是所有时候都是尽量使用const比较好。在返回值（非引用）的时候，const 返回值目前大部分情况下并不是一个很好的选择。参考的是stackoverflow的[另一个讨论](https://stackoverflow.com/questions/8716330/purpose-of-returning-by-const-value)，和这个讨论指向的[另一个](https://stackoverflow.com/questions/6299967/what-are-the-use-cases-for-having-a-function-return-by-const-value-for-non-built)。

总之，非常感谢总结！

**Comment by huihut** [comment]
感谢。
1. 我改成 `编译器一般不内联包含循环、递归、switch 等复杂操作的内联函数` 了，
2. 这个看使用场景吧，`尽可能使用 const` 也不是一味地使用。
