### ISSUE TITLE
平衡二叉树的概念

### ISSUE THREAD

**Issue by HowsonLiu** [huihut/interview#36]
在[平衡二叉树](https://github.com/huihut/interview/blob/master/README_Details.md#%E5%B9%B3%E8%A1%A1%E4%BA%8C%E5%8F%89%E6%A0%91avl%E6%A0%91)这里
> 平衡二叉树必定是二叉搜索树，反之则不一定     

平衡二叉树一定是二叉搜索树吗？不是二叉搜索树的树也能平衡的吧？

**Comment by Perry961002** [comment]
平衡二叉树也叫平衡二叉搜索树，是在普通的二叉搜索树的基础上加上对子树高度差的限制得到的，作者说的是对的

**Comment by HowsonLiu** [comment]
的确如此，学习了😝
