### ISSUE TITLE
经过实验发现可以取得this的地址

### ISSUE THREAD

**Issue by naijim** [huihut/interview#4]
感谢这份教程，写的很详尽。

在`this指针`那一节中说，“由于 this 并不是一个常规变量，所以，不能取得 this 的地址”。写了一个测试程序，发现可以取得this的值，如有错误还请指正。

```
#include <iostream>

class Foo
{
  public:
  void print_foo()
  {
    std::cout << this << std::endl;
  }
};

int main()
{

  Foo obj;
  obj.print_foo();
  return 0;
}
```

**Comment by huihut** [comment]
你的测试程序输出的是 obj 对象的地址（this 的值），而 “由于 this 并不是一个常规变量，所以，不能取得 this 的地址” 的意思是不能取 `&this`，因为 `this` 是个 `右值`。抱歉文中表达不清楚让你误解了。可以参考：[stackoverflow . address of this](https://stackoverflow.com/questions/9114930/address-of-this)

**Comment by naijim** [comment]
感谢, issue closed
