### ISSUE TITLE
链接挂了

### ISSUE THREAD

**Issue by zkangHUST** [huihut/interview#45]
C 语言实现封装、继承和多态 这个链接挂了

**Comment by huihut** [comment]
请问是哪个链接？是9天前改好了的吗？https://github.com/huihut/interview/commit/6dd52daea4db1d4843f58050f60a3312bcafc0cf

**Comment by zkangHUST** [comment]
前两天看的时候，有一个链接文字是 “C 语言实现封装、继承和多态 ”， 今天看的时候好像已经被替换掉了。 never mind.
