### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by ShayekhBinIslam** [huihut/interview#60]
Is English Version available? If not may I translate this repository/site? Thanks.

**Comment by huihut** [comment]
There is no English version now, you are welcome to translate this repo.

**Comment by huihut** [comment]
If there are other friends who want to translate this repo into English, you can communicate here.

**Comment by huihut** [comment]
The English version should be in the root directory with the name `README_en.md`

**Comment by ShayekhBinIslam** [comment]
Thanks. Please assign me. I am translating alone now..

**Comment by huihut** [comment]
@ShayekhBinIslam 
I read your translation repository <https://github.com/ShayekhBinIslam/interview>, the translation is good, can you submit a PR to merge here? It can be shared with more people. 

The English version is named `README_en.md`

**Comment by ShayekhBinIslam** [comment]
Thanks. I will try to review it and finalize within couple of days.
