### ISSUE TITLE
普通对象可以更新常成员变量??

### ISSUE THREAD

**Issue by ifls** [huihut/interview#77]
c++  const 这一节
A b;                        // 普通对象，可以调用全部成员函数、更新常成员变量

**Comment by huihut** [comment]
当常成员变量是指针的时候可以更新，具体在 [这个issue](https://github.com/huihut/interview/issues/41) 讨论过。

**Comment by huihut** [comment]
这里确实错了，常成员变量不能被更新，已改

**Comment by jinfeihan57** [comment]
如果函数以mutable修饰，就可以修改const成员变量了。
