### ISSUE TITLE
关于STL内存分配器的描述

### ISSUE THREAD

**Issue by sniper00** [huihut/interview#8]
```小于 128Bytes 使用一个 8Bytes 倍数的数组来进行申请（原因是为了提高效率，同时对于 64 位的机器而言，地址大小为 8Bytes）```

不知道你是不是看的侯捷的书，那本书太老了。你可以看下较新版的C++实现，直接调用的new delete

**Comment by huihut** [comment]
确实是侯捷《STL源码剖析》的概念，60页二级配置器，小于128bytes以内存池管理。

我看SGISTL的实现（[stl_alloc.h](http://labmaster.mi.infn.it/Laboratorio2/serale/www.sgi.com/tech/stl/stl_alloc.h)）还是这样的：
```cpp
  static void* allocate(size_t __n)
  {
    void* __ret = 0;

    if (__n > (size_t) _MAX_BYTES) {
      __ret = malloc_alloc::allocate(__n);
    }
    else {
      _Obj* __STL_VOLATILE* __my_free_list
          = _S_free_list + _S_freelist_index(__n);
      // Acquire the lock here with a constructor call.
      // This ensures that it is released in exit or during stack
      // unwinding.
#     ifndef _NOTHREADS
      /*REFERENCED*/
      _Lock __lock_instance;
#     endif
      _Obj* __RESTRICT __result = *__my_free_list;
      if (__result == 0)
        __ret = _S_refill(_S_round_up(__n));
      else {
        *__my_free_list = __result -> _M_free_list_link;
        __ret = __result;
      }
    }

    return __ret;
  };
```
不知道您说的`较新版的C++实现，直接调用的new delete`是什么意思，在哪里可以看到？

**Comment by sniper00** [comment]
侯捷讲的哪种实现 主流编译期已经没有用的了，你可以看下 gcc, 或者 vs的源码 ，一般就是直接调用的new,delete。
如vs2017的实现：
- allocator 部分代码
```
			const uintptr_t _Ptr_container =
				reinterpret_cast<uintptr_t>(::operator new(_Block_size));
			_SCL_SECURE_ALWAYS_VALIDATE(_Ptr_container != 0);
			void * const _Ptr = reinterpret_cast<void *>((_Ptr_container + _Non_user_size)
				& ~(_Big_allocation_alignment - 1));
			static_cast<uintptr_t *>(_Ptr)[-1] = _Ptr_container;
```
- deallocate 部分代码
```
		if (_Align > __STDCPP_DEFAULT_NEW_ALIGNMENT__)
			{
			::operator delete(_Ptr, _Allocated_size, align_val_t{_Align});
			}
		else
 #endif /* _HAS_ALIGNED_NEW */
			{
			::operator delete(_Ptr, _Allocated_size);
			}
```

gcc的你可以自己看一下

**Comment by huihut** [comment]
确实是，就算对齐也是用 `void* T::operator new  ( std::size_t count, std::align_val_t al );` 底层是 `_aligned_malloc`，最终还是`malloc`，没有自由链表什么的了。学习了。

* VS：`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include\xmemory0`
* GCC：[gcc/libstdc++-v3/include/ext/new_allocator.h](https://github.com/gcc-mirror/gcc/blob/1143dcb41617e18796fa3f68f1d3d409ee9ab03a/libstdc%2B%2B-v3/include/ext/new_allocator.h#L111)
